server:
  port: 8092
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zscyun?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: zscyun
    password: zscyun724318787
# mybatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  # Mybatis开启驼峰映射

dataFormatter:
  dataFormatterStyleOne: yyyy-MM-dd HH:mm:ss
  dataFormatterStyleTwo: yyyy/MM/dd
  dataFormatterStyleThree: yyyy-MM-dd







